#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $TEEWORLDSDIR = "/home/twowner";
my $SCREENCMD = "/usr/bin/screen";

# No changes below here...

my $exists = "";

# Set ENV vars
$ENV{'TERM'} = "xterm-256color";

my $running=`ps ax|grep "teeworlds-server"|grep -v grep`;

while (-1)
{
	chdir $TEEWORLDSDIR;
	# check if Teeworlds server process is running
	#$running=`ps ax|grep "./Server --headless"|grep -v grep`;
	$running=`ps ax|grep "teeworlds-server"|grep -v grep`;
	if ($running eq "")
	{
		print "Teeworlds server not running\n";
		# See if they want the server started
		if (! -f "$TEEWORLDSDIR/nostart")
		{
			# The Log Entry
			my $datestring = localtime();
			my $TIME="Teeworlds server Down, Restarting: $datestring";
			open(OUTF, ">>$TEEWORLDSDIR/TeeworldsScreen.log") || die "Unable to open $TEEWORLDSDIR/TeeworldsScreen.log for appending";
			print (OUTF "$TIME\n");
			close($OUTF);
			chdir "$TEEWORLDSDIR";
			print "Starting screen process\n";
			system("$SCREENCMD -fa -S Teeworlds -d -U -m /usr/games/teeworlds-server -f $TEEWORLDSDIR/teeworlds_srv.cfg");
		}
	}
	# Sleep for 1 minute before checking again
	sleep(60);
}
exit(0);
