#!/usr/bin/perl

### BEGIN INIT INFO
# Provides:          teeworlds
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Teeworlds service 1.0
# Description:       Teeworlds service 0
# Documentation:     https://GamePlayer.club
# Type:              forking
# X-Interactive:     false
### END INIT INFO

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $TEEWORLDSDIR = "/home/twowner/twserver";

my $Command = $ARGV[0];
if ($Command eq "")
{
	$Command = "NONE";
}

my $running=`ps ax|grep "teeworlds_srv"|grep -v grep`;

if ($Command eq "start")
{
	if ($running eq "")
	{
		print "Starting Teeworlds Server...\n";
		if (-f "$TEEWORLDSDIR/nostart")
		{
			print "Removing $TEEWORLDSDIR/nostart\n";
			# Remove the lock file if it exists
			unlink("$TEEWORLDSDIR/nostart");
		}
		# Start the screen process
		system("/usr/bin/nohup $TEEWORLDSDIR/startteeworlds > $TEEWORLDSDIR/TeeworldsStartup.log\&");
	}
}
elsif ($Command eq "stop")
{
	print "Stopping Teeworlds Server Process...\n";
	system("touch '$TEEWORLDSDIR/nostart'");
	if ($running ne "")
	{
		# Process is running, kill it
		system("killall \"teeworlds_srv\"");
	}
}
elsif ($Command eq "restart")
{
	if (-f "$TEEWORLDSDIR/nostart")
	{
		print("Removing $TEEWORLDSDIR/nostart\n");
		unlink("$TEEWORLDSDIR/nostart");
	}
	if ($running ne "")
	{
		system("killall \"teeworlds_srv\"");
	}
}
elsif ($Command eq "status")
{
	if ($running ne "")
	{
		print("Teeworlds Server Running\n");
	}
	else
	{
		print("Teeworlds Server Not Running\n");
	}
}
else
{
	print ("Uknown command '$Command'\n");
	print ("Usage: $0 {start|status|stop|restart}\n");
	exit(1);
}

exit(0);
